package Node

type Row struct {
	ClientID                string
	MainAccountID           string
	ClientSequence          int64
	Name                    string
	ClientIP                string
	BaseURL                 string
	DockerAPIURL            string
	OS                      string
	Arch                    string
	CPUCores                int64
	MemoryTotalMB           int64
	DockerVersion           string
	HealthStatus            string
	DiscoveryStatus         string
	DiscoveryReason         string
	PushStatus              string
	TargetSlotCount         int64
	ActualSlotCount         int64
	AvailableSlotCount      int64
	RunningSlotCount        int64
	SlotExceptionStatus     string
	SlotExceptionReason     string
	LastSlotCheckedAt       int64
	APIKeyHash              string
	LastDiscoveredAt        int64
	LastHeartbeatAt         int64
	LastHeartbeatReportedAt int64
	LastHeartbeatSource     string
	LastCheckedAt           int64
	LastError               string
	CreatedByUserID         string
	CreatedByUsername       string
	CreatedAt               int64
	UpdatedAt               int64
	DeletedAt               int64
}
